### ISSUE TITLE
Pre-build f90wrap wheels for windows

### ISSUE THREAD

**Issue by Borrdom** [jameskermode/f90wrap#169]
Hi, James. Thank you so much for this great package. I successfully wrapped a big fortran project with minimal changes to the actual code.
The wrapper works perfectly and now I want to use it on a different user's machine. When using f2py only, I just provide a pre-build wheel with the binaries ( *.so or *.pyd files) suitable for the user's python version and architecture. This way, the user does not need to install a fortran compiler. However, when using f90wrap, the user needs to install f90wrap which requires a fortran compiler. Of course, this is necessary because f90wrap.runtime.py relies on the arraydata.f and sizeof_fortran_t.f fortran files. 
In a sloppy approach i just copied my own PYHONHOME\Lib\site-packages\f90wrap folder into the same folder on the user's machine where the wrapped MODULE.py and _MODULE.pyd files reside and it just worked.
Are there plans to provide pre-build versions of f90wrap. Similar to those source and binary wheels that scipy provides?

**Comment by jameskermode** [comment]
Thanks for the feedback and I'm glad 

[Binary wheels](https://pypi.org/project/f90wrap/#files) have been available for Linux and macOS for the last few release of f90wrap (since 0.2.5). Does this meet your use case? 

If you need wheels for a different architecture (e.g. Windows) then please let me know; PRs to add support for new architectures to the [cibuildwheel configuration](https://github.com/jameskermode/f90wrap/blob/master/.github/workflows/build-wheels.yml) would be particularly welcome.

**Comment by Borrdom** [comment]
Thanks for the fast response. Ahh I see. I'm running windows (64 bit with py 3.9) which explains why i didn't get a binary wheel via pip. Sure, i think binary wheels for windows would be helpful. I'm currently looking into cibuildwheel for the use in my own project so maybe i can contribute with a PR. 
I can rename the issue to highlight that it is only windows specific or close it ?

**Comment by jameskermode** [comment]
Please go ahead and rename the issue, good idea.
