### ISSUE TITLE
Symbols not found

### ISSUE THREAD

**Issue by MrYann** [jameskermode/f90wrap#45]
With the following command lines, the module compiles, but can not be imported in python because "Symbol not found" for the functions inside the module : 

	f90wrap -v -m maxwell functions.f90
	f2py3 -c -m _maxwell f90wrap*.f90

If I add *.o to the f2py3 command, it works with a minimal test case. However, with the complex fortran code I am trying to use, the commands

	f90wrap -v -m maxwell functions.f90
	f2py3 -c -m _maxwell f90wrap*.f90 *.o

the "import maxwell" command produces the error "Symbol not found: _f90wrap_abort_".

So i can have a link to my own functions or to the f90wrapper functions, but not both. What am i doing wrong ?

**Comment by jameskermode** [comment]
The second invocation, with the object files included, is correct.

The `f90wrap_abort` symbol is added by the patched version of `f2py` distributed with `f90wrap`, which is named `f2py-f90wrap` - please use this instead of `f2py3`. 

This mechanism allows exceptions to be raised inside Fortran code and be propagated back to Python.

**Comment by MrYann** [comment]
Hallelujah !

	f90wrap -v -m maxwell *.f90
	f2py-f90wrap -c -m _maxwell f90wrap*.f90 *.o

did it !
